- package.json
- src/style.css
- tailwind.config.js
- yarn.lock
- resolved #9
- @toast-ui/react-editor 설치
- @uiw/react-md-editor 제거
> chore: yarn add @toast-ui/react-editor

- src/components/ui/input.tsx
- tailwind.config.js
- resolved #8 
- shadcn/ui의 input 컴포넌트를 수정하여서 제작하였습니다.
- `isInvalid props` : error인 상황에서 isInvalid = true 값을 넣어주면, error input 컴포넌트가 표시됩니다.
- `isDisabled props` : 입력이 불가능하게 됩니다. (혹시 모를 상황을 위해서 제작해둠..)
- focus, active 상황에 맞추어 css 수정하였습니다.
> feat: Input 컴포넌트 개발

- src/containers/common/Footer.tsx/Footer.tsx
- src/pages/main/containers/MainScheduleSection.tsx
- tailwind.config.js
- resolved #18 
- Footer 컴포넌트가 없어서 반응형 반영하여 제작 완료했습니다.
- MainScheduleSection 컴포넌트 css를 변경하여 반응형 추가하였습니다.
- Footer의 위치와 높이 관련된 부분은 page 제작하면서 수정하겠습니다!
- 메인 페이지 제작
> refactor: footer, dday 컴포넌트 반응형 추가

- src/components/Buttons/BoardActionButtons.tsx
- src/components/Category/index.tsx
- src/components/Search/Search.tsx
- src/containers/common/Header/Header.tsx
- resolved #28
Category/index.tsx 파일 반응형 수정
Buttons/BoardActionButtons.tsx ...props 속성 추가
Search.tsx 반응형 재조정
Header.tsx z-index 속성 추가
페이지 작업 하다보니 기존 컴포넌트들 반응형 설정이 잘못된게 있었네요ㅠ  급하게 수정해서 올립니다!
> fix: fix reactive and style props

- package.json
- src/components/PostHead/index.tsx
- src/components/Spacing/index.tsx
- src/utils/formatYYYYMMDDHHMM.ts
- yarn.lock
- resolved #30 
- `date-fns` 설치
- `formatYYYYMMDDHHMM` 생성 (src/utils 폴더 내부에 위치 ! 다른 곳에서 날짜 변환 필요할 때 사용해주세요 !)
- `Spacing` 생성 (다른 곳에서 간격 조정할 때 사용해주세요, gap 사용 애매 + 가시적으로 코드에서 간격이 드러나야 하는 경우 사용 !)
- `PostHead` 생성
예시 )
```
<PostHead
title="[US:SUM] 2월 활동보고집"
writer="중앙집행위원회"
date="2021-11-08T11:44:30.327959"
/>
```
> feat: PostHead component 추가

- src/pages/audit/page.tsx
- src/pages/general/page.tsx
- src/pages/intro/page.tsx
- src/pages/kakao/page.tsx
- src/pages/main/page.tsx
- src/pages/router.tsx
- resolved #58
브라우저
코드
모든 페이지에 Header를 다 제거했습니다!
> feat/Header Layout화

- src/apis/client.ts
- src/pages/audit/page.tsx
일단 인스턴스만 생성했습니다. 인터셉터 이슈 새로 파겠습니다.
- resolved #60
> feat: src/apis/client.ts commit

- src/components/PostTextPetition/index.tsx
- src/components/PostTextPetition/types/index.ts
- resolved #73
PostTextPetition 컴포넌트의 props 와 타입 수정 및 StateTag switch 분기점 변경
> fix: posttextpetition props, 타입 수정

- src/vite-env.d.ts
> docs: remove vite env

- .gitignore
- src/apis/getBoardPosts.ts
- src/components/PostTextPetition/index.tsx
- src/components/PostTextPetition/types/index.ts
- src/hooks/useGetBoardPosts.ts
- src/types/apis/get/index.tsx
- src/types/getPetitionTopLiked.ts
- src/vite-env.d.ts
- resolved #86
vite-env.d.ts 설정해서 다시 올렸습니다.. 죄송함다..
getBoardPosts 함수를 다른 게시판 페이지에서도 사용할 수 있도록 변경하였습니다!
(@jongse7 함수 내용을 조금 변경해서 기존에 짜두신 코드 수정 부탁드려요!)
PostTextPetition 컴포넌트 변경
> fix: PostTextPetition component error

- package.json
- src/pages/data/containers/dataBoxSection.tsx
- src/pages/data/containers/edit/UploadSection.tsx
- src/pages/general/containers/CertifyApplySection.tsx
- src/pages/general/containers/GeneralRegisterSection.tsx
- src/pages/general/containers/index.ts
- yarn.lock
- resolved #101 
- type 에러 나는 거 다 잡았습니다
> fix : 로그인, 자료집 오류해결

- src/components/Breadcrumb/index.tsx
- src/components/Comment/Comment.tsx
- src/components/MainCarousel/index.tsx
- src/components/TextArea/TextArea.tsx
- src/containers/common/Header/component/AuthButton.tsx
- src/containers/common/Header/component/HeaderSheet.tsx
- src/containers/common/Header/const/pathData.tsx
- src/pages/audit/auditDetail/container/auditDetailEditSection.tsx
- src/pages/audit/auditDetail/utils/locationHandler.ts
- src/pages/audit/auditEdit/hook/useAuditEdit.ts
- src/pages/audit/const/data.ts
- src/pages/audit/page.tsx
- src/pages/audit/utils/cardHandler.ts
- src/pages/audit/utils/categoryHandler.ts
- src/pages/data/containers/DataTitleSection.tsx
- src/pages/data/containers/dataEditBtn.tsx
- src/pages/data/containers/edit/UploadSection.tsx
- src/pages/data/page.tsx
- src/pages/general/containers/CertifyApplySection.tsx
- src/pages/general/containers/CertifyErrorSection.tsx
- src/pages/general/containers/GeneralRegisterSection.tsx
- src/pages/intro/container/IntroEditButton.tsx
- src/pages/intro/container/hooks/useQueryMap.ts
- src/pages/intro/container/hooks/useValidateAndRedirect.ts
- src/pages/intro/container/utils/switchUtils.ts
- src/pages/kakao/containers/KakaoRedirect.tsx
- src/pages/petition-notice/[id]/containers/PostPetitionDetailPostSection.tsx
- src/pages/petition-notice/containers/PopularSection/PetitionNoticePopularSection.tsx
- src/pages/petition-notice/containers/PostSection/PetitionPostSection.tsx
- src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
- resolved #104 
- 테스트 배포를 위해 base url을 ' / ' 에서 ' /homepage-frontend '로 변경했습니다
- 혹시나 변경되지 않은 부분이 있으면 추가 변경 예정입니다.
> fix : base url 설정 변경

- src/App.tsx
- src/pages/general/containers/GeneralRegisterSection.tsx
- resolved #106 
- 로그인 로직 분리 (자치기구, 일반)
> fix : 자치기구, 일반 로그인 post 로직 분리

- src/apis/delBoardPosts.ts
- src/components/Carousel/index.tsx
- src/components/PostContent/PetitionPostContent.tsx
- src/components/PostTextPetition/index.tsx
- src/components/Search/Search.tsx
- src/pages/main/containers/PetitionSection.tsx
- src/pages/petition-notice/[id]/containers/PostPetitionDetailPostSection.tsx
- src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
- resolved #110 
반응형 수정
파일 삭제 api request body에 파일(이미지) url 추가하는 형식으로 변경되어 해당 부분 수정했습니당
> Fix/#110 toast UI delete image

- src/apis/patchBoardPosts.ts
- src/components/Comment/Comment.tsx
- src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
- src/types/patchBoardPosts.ts
- resolved #114
게시글 수정 시 사용하는 patch api request body에 이미지 id 값 포함 로직으로 수정했습니다
> fix: patch api 수정

- src/hooks/useDelBoardPosts.ts
- resolved #116 
useDelBoardPosts 타입 에러 수정
> fix: type error fix

- src/pages/petition-notice/containers/PopularSection/PetitionNoticePopularSection.tsx
- src/pages/petition-notice/containers/PostSection/PetitionPostSection.tsx
- resolved #135 
- 
청원게시판 게시물 리스트 없을 시 상황 처리
> feat: 청원페이지 post null 처리

- src/components/PostCard/PostCardNotice.tsx
- src/components/ui/select.tsx
- src/containers/common/Header/component/HeaderSheet.tsx
- src/pages/audit/auditDetail/container/auditDetailFileSection.tsx
- src/pages/audit/auditDetail/page.tsx
- src/pages/audit/auditEdit/container/auditEditTitleSection.tsx
- src/pages/audit/auditPatch/container/auditPatchFileSection.tsx
- src/pages/audit/auditPatch/hook/useAuditPatch.ts
- src/pages/audit/auditPatch/page.tsx
- src/pages/lost-article/detail/page.tsx
- src/pages/lost-article/patch/hook/useLostPatch.ts
- src/pages/main/containers/CampusMapSection.tsx
- src/pages/main/containers/LostArticleSection.tsx
- src/pages/main/containers/NoticeSection.tsx
- src/pages/main/containers/PetitionSection.tsx
- src/pages/notice/component/NoticeContent.tsx
- src/pages/notice/noticeDetail/container/noticeDetailEditSection.tsx
- src/pages/notice/noticeDetail/container/noticeDetailFileSection.tsx
- src/pages/notice/noticeDetail/page.tsx
- src/pages/notice/noticePatch/hook/useNoticePatch.ts
- src/pages/notice/noticePatch/page.tsx
- src/pages/notice/utils/cardHandler.ts
- src/pages/partnership/page.tsx
- src/pages/partnership/partnershipDetail/container/PartnershipDetailFileSection.tsx
- src/pages/partnership/partnershipDetail/page.tsx
- src/pages/partnership/partnershipEdit/component/ImageDropzone.tsx
- src/pages/partnership/partnershipEdit/container/PartnershipEditTitleSection.tsx
- src/pages/partnership/partnershipPatch/hook/usePartnershipPatch.ts
- src/pages/partnership/partnershipPatch/page.tsx
- src/types/apis/get/index.tsx
> fix: qa 진행

- build.sh
> feat: Create build.sh

- .github/workflows/deploy.yml
> chore: .github/workflows/deploy.yml

- src/pages/general/containers/CertifyApplySection.tsx
- src/pages/general/containers/GeneralRegisterSection.tsx
- src/pages/general/containers/index.ts
- src/pages/kakao/containers/RegisterButtonSection.tsx
- src/pages/kakao/containers/RegisterTextSection.tsx
- src/style.css
- resolved #(issue_num)
- 51번 QA 제외한 39, 49, 50, 53 번 QA 진행했습니다. 
- 51번 QA  논의 이후 해결 예정입니다.
> 로그인 1차 QA 완료

- src/pages/kakao/containers/RegisterButtonSection.tsx
- resolved #158 
카카오 리다이렉트 uri에 service terms 추가
> fix: kakao service-terms 파라미터 수정:

- src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
- resolved #162 
useEffect 의존성 수정
> fix: title 수정 안되는 버그 수정

- src/components/PostCard/PostCardBasicMissing.tsx
- src/pages/notice/component/NoticeContent.tsx
> 공지사항 게시글 new 추가

- src/components/ui/dialog.tsx
- src/pages/general/containers/TOSSectioin.tsx
- resolved #172 
약관 동의 컴포넌트 너비, 높이 재조정
> feat: 약관 동의 너비 높이 재조정

- src/pages/data/containers/dataBoxSection.tsx
- src/pages/data/containers/edit/UploadSection.tsx
- resolved #178
- 자료집 오류 해결했습니다.
> fix : 공지 여러개 생성 오류 해결

- src/pages/layout/headerLayout.tsx
- src/pages/main/containers/LostArticleSection.tsx
- src/pages/main/page.tsx
> feat: footer 전 페이지 적용

- src/pages/main/containers/LostArticleSection.tsx
- src/pages/notice/hooks/useNoticeToday.ts
- src/pages/notice/page.tsx
- src/pages/partnership/page.tsx
- src/template/board/BoardContent.tsx
- src/template/board/boardData.ts
- tsconfig.json
> fix: useNoticeToday category, subcategory 비갱신 문제 해결

- src/apis/getBoardPosts.ts
- src/pages/notice/hooks/useNoticeToday.ts
- src/pages/notice/noticeEdit/hook/useNoticeEdit.ts
- src/pages/notice/page.tsx
- src/template/board/BoardContent.tsx
- src/template/board/boardData.ts
> fix: useCurrent

- index.html
> chore: 번역 제거

- src/apis/getBoardPosts.ts
> style: MainScheduleSection 반응형

- src/pages/notice/noticeEdit/container/noticeEditTitleSection.tsx
> fix:배포 시 edit창 inpu두번 입력 에러

- src/pages/audit/auditEdit/container/auditEditTitleSection.tsx
- src/pages/notice/noticeEdit/container/noticeEditTitleSection.tsx
> fix:배포 시 edit창 inpu두번 입력 에러 픽스

- src/pages/general/containers/TOSSectioin.tsx
- resolved #247 
TOSSection.tsx 의 button 태그의 disabled 속성 제거
> feat: 약관 동의 로직 수정

- src/pages/general/components/TOSContent.tsx
- src/pages/personal-data/component/emailContent.tsx
- src/pages/personal-data/component/personalDataContent.tsx
- src/pages/personal-data/component/termsOfServiceContent.tsx
- src/pages/personal-data/container/contentSection.tsx
> feat: 약관 동의 날짜 수정

- src/pages/personal-data/page.tsx
- resolved #253 
personal-data/page.tsx 제목 수정
> fix: 개인 정보 처리 방침 타이틀 변경

- src/pages/kakao/containers/KakaoRedirect.tsx
> hotfix: 카카오 로그인 성공 시 강제 리다렉

- src/App.tsx
- src/containers/common/Header/component/HeaderSheet.tsx
> hotfix: 카카오 로그인 리다렉 버그 수정

- src/pages/kakao/containers/KakaoRedirect.tsx
> hotfix: 라우팅 수정

- src/pages/kakao/containers/KakaoRedirect.tsx
- src/pages/kakao/redirect/containers/RegisterButtonSection.tsx
> feat: 기존 회원가입 사용자 flow

- src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx
> hotfix: 청원 글 수정 isNotice 속성 추가

- src/pages/audit/auditDetail/container/auditDetailContentSection.tsx
- src/pages/notice/noticeDetail/container/noticeDetailContentSection.tsx
- src/pages/partnership/hook/usePartnership.ts
- src/pages/partnership/page.tsx
- src/pages/partnership/partnershipDetail/container/PartnershipDetailContentSection.tsx
- src/template/board/BoardContent.tsx
> fix: 이미지 가로 고정 및 제휴게시판 게시글 레이아웃 조정

- src/App.tsx
- src/apis/client.ts
- src/containers/common/Header/Header.tsx
- src/containers/common/Header/component/HeaderSheet.tsx
- src/pages/general/containers/GeneralRegisterSection.tsx
- src/pages/kakao/containers/KakaoRedirect.tsx
- src/pages/layout/headerLayout.tsx
- src/pages/router.tsx
> chore: /beta 코드 삭제

- src/pages/lost-article/detail/container/lostDetailTopSection.tsx
- src/pages/lost-article/detail/page.tsx
> refactor: 분실물게시판 학번 적용

- src/pages/index.ts
- src/pages/router.tsx
> feat: 이외 경로 루트 경로로 리다이렉트 처리

- src/components/ui/input.tsx
- src/pages/general/containers/GeneralRegisterSection.tsx
> style: GeneralRegister input, button padding, 상단 문구 크기 조절

- src/pages/audit/page.tsx
> chore: vercel 브랜치 promotion용 commit

- src/pages/audit/auditEdit/container/auditEditTitleSection.tsx
- src/pages/notice/noticeEdit/container/noticeEditTitleSection.tsx
- src/pages/partnership/partnershipEdit/container/PartnershipEditTitleSection.tsx
> refactor: 게시글 제목 제한 50자 => 80자

- src/pages/human-rights/edit/page.tsx
- src/pages/human-rights/schema.ts
> fix(human-rights): 변경된 스키마 대응

- src/pages/human-rights/schema.ts
- 백엔드 수정 스키마의 rightsDetailId 삭제를 반영했습니다.
> fix(human-rights): 스키마에서 rightsDetailId 제거

- src/pages/human-rights/edit/page.tsx
- related: #338
게시물 수정 후 게시물 쿼리가 무효화되도록 했습니다.
> feat(human-rights): 게시물 수정 후 쿼리 무효화

- src/hooks/useContentEditor.ts
- src/pages/human-rights/edit/page.tsx
- 수정 화면 진입 시 포커스가 에디터에 가있는 문제 해결
> fix(human-right): no autofocus on editor init

- src/pages/human-rights/[id]/page.tsx
> fix(human-rights): 자치기구의 댓글 삭제 금지

- src/pages/human-rights/edit/page.tsx
> fix(human-rights/edit): 피침해자 목록과 침해자 목록의 레이아웃이 다름

- src/pages/human-rights/page.tsx
- 페이지, 카테고리 이동 시 스크롤이 고정되는 현상을 해결했습니다.
강제로 스크롤을 초기화 하였습니다. 추후 원인 파악 후 해결 필요합니다.
> fix(human-rights): 페이지, 카테고리 이동 시 스크롤 초기화

- src/pages/human-rights/edit/components/FileInput.tsx
- src/pages/human-rights/edit/components/FileInputs.tsx
- src/pages/human-rights/edit/page.tsx
- src/pages/human-rights/edit/utils.ts
> fix(human-rights): 파일 크기가 5MB 이상일 때 업로드 방지

- package.json
- src/pages/human-rights/edit/components/FrontmatterEditor.tsx
- src/pages/human-rights/edit/components/FrontmatterInput.tsx
- src/pages/human-rights/edit/page.tsx
모바일 환경에서 글과 입력이 화면 영역을 넘어가는 문제 수정
- related: #338
> fix(human-rights/edit): 모바일 환경 반응형 수정

- src/pages/human-rights/edit/components/FileInput.tsx
> fix(human-rights/edit): 파일 업로드 가시성 개선

- src/pages/human-rights/edit/page.tsx
- src/pages/human-rights/schema.ts
> fix(human-rights/edit): 제목이 50자 이상일 시 오류 표시

- src/containers/common/Header/component/DropDownMenu.tsx
- src/containers/common/Header/component/HeaderSheet.tsx
- src/containers/common/Header/component/Navigation.tsx
- src/pages/main/containers/LostArticleSection.tsx
- src/pages/main/containers/MainScheduleSection.tsx
- yarn.lock
> fix: D-Day 변경

- src/pages/main/containers/MainScheduleSection.tsx
> hotfix: d-day 수정

- src/pages/mypage/service-notice/[id]/container/serviceNoticeDetailEditSection.tsx
- src/pages/mypage/service-notice/component/ServiceNoticePostContent.tsx
- src/pages/mypage/service-notice/page.tsx
- src/pages/notice/noticeEdit/hook/useNoticeEdit.ts
- resolved #380 
서비스공지사항 게시판 text 수정
게시물 생성 시 제한 조건 수정
생성 후 목록이 아닌 그 해당 게시글로 이동하도록 변경
> refactor: 서비스공지사항 폰트 수정

- .github/workflows/deploy-dev.yml
- package.json
- resolved #387 
EC2에 서비스를 배포합니다. 워크플로 등록을 위해 main에 머지
배포 URL:
- (develop) [https://dev.sssupport.shop](https://dev.sssupport.shop)
- (production) [https://sssupport.shop](https://sssupport.shop) - 추후 `stu.ssu.ac.kr`에도 연결 예정
@jongse7 프로덕션에서 `VITE_REST_API_KEY` 값 설정이 필요합니다. 나중에 전달 해주시거나 아니면 `prod` environment에 `VITE_REST_API_KEY` 시크릿 업데이트 후 알려주세요.
> ci: EC2에 서비스 배포

- .github/workflows/deploy-dev.yml
- package.json
- resolved #387 
develop과 main 일치를 위해 머지
배포 URL:
- (develop) [https://dev.sssupport.shop](https://dev.sssupport.shop)
- (production) [https://sssupport.shop](https://sssupport.shop) - 추후 `stu.ssu.ac.kr`에도 연결 예정
@jongse7 프로덕션에서 `VITE_REST_API_KEY` 값 설정이 필요합니다. 나중에 전달 해주시거나 아니면 `prod` environment에 `VITE_REST_API_KEY` 시크릿 업데이트 후 알려주세요.
> ci: EC2에 서비스 배포 (#395)

- src/components/BoardNew/edit/FileInput.tsx
- resolved #410 
FileInput 컴포넌트 내 FileterDropDown 버튼의 위치를 변경했습니다.
> refactor: FileInput 내 FilterDropDown 컴포넌트 위치 변경

- src/pages/general/containers/GeneralRegisterSection.tsx
- resolved #430 
첫 회원가입 시 패슈 callback 페이지로 이동할 때 딜레이가 생기면 총학 메인페이지로 가지는 이슈가 있어 이를 방지했습니다
> fix: passu 리다이랙트 대응

- src/components/File/FileDownButton.tsx
- src/pages/data/edit/page.tsx
- src/pages/data/hook/mutation/useCreateDataPost.ts
- src/pages/data/hook/mutation/usePatchDataPost.ts
- src/pages/data/schema.ts
> refactor: 구자료집일 때 확장자명 생략 #455

- src/components/PostCard/PostCardBasicMissing.tsx
- src/components/PostCard/const/style.tsx
- src/pages/notice/component/NoticeNavSection.tsx
> refactor: PostCard 컴포넌트 글자 수 제한 변경

- src/components/PostCard/PostCardBasicMissing.tsx
> feat: subtitle의 태그 지우기 #460

- src/components/PostCard/const/style.tsx
- src/pages/notice/hooks/useNoticeToday.ts
> style: postcard small 스타일 조정

- src/pages/data/schema.ts
> fix: 자료집 상세 조회 시 category에 null이 들어가 zod error가 뜨는 이슈

- src/containers/common/Header/Header.tsx
> fix: 메인 카러셀의 잘못된 z-index 수정

- src/pages/qna-notice/page.tsx
#493 을 develop에 머지합니다.
- resolved #(issue_num)
> chore: main 변경사항 적용

- src/pages/data/page.tsx
> fix(data): 자료집 글쓰기 링크 수정

- src/pages/data/page.tsx
`md-xl` breakpoint에서 검색창이 표시되지 않는 문제 수정
> fix(data): search input in md-xl breakpoint

- src/pages/general/containers/GeneralRegisterSection.tsx
> fix: 온보딩(로그인) 시 입력 창 패딩 수정

- src/atoms/atom.ts
- src/containers/common/Header/Header.tsx
- src/containers/common/Header/component/HeaderSheet.tsx
> fix: HeaderSheet의 로그인 상태 동기화

- src/pages/layout/registerLayout.tsx
- src/pages/register/step/scouncil/page.tsx
> fix: 로그인 성공 시 토큰 저장 로직 추가

- .github/workflows/ci.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy.yml
- package.json
preview 배포를 추가하여 PR 내용을 로컬이 아니여도 확인할 수 있도록 합니다.
아래 사진에서 우상단 View Deployment 버튼을 클릭하면 확인할 수 있습니다.(or https://dev-preview.sssupport.shop 접속)
> ci: Preview 배포

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy.yml
- `MIXPANEL_TOKEN`이 들어가지 않는 문제 수정
> fix: `MIXPANEL_TOKEN`이 들어가지 않는 문제 수정

- src/apis/client.ts
- src/hooks/new/query/useSearchPosts.ts
- src/pages/data/hook/query/useSearchDataPost.ts
[QA](https://discord.com/channels/1221431238041272401/1373485523120816232/1373485523120816232) 문제 해결
> fix: 특정 게시판에서 특수문자를 포함한 검색이 불가능한 문제 수정

- .github/workflows/deploy.yml
1️⃣ 작업 내용 Summary
resolved #571
백엔드 요청에 따라 deploy.yml을 수정하여 S3 + CloudFront + EC2 병행 배포가 가능하도록 설정했습니다.
(기타)
AWS_ASSUME_ROLE_ARN 값을 secret으로 처리
변수 이름 가독성 개선 (HOMEPAGE_FE_BUCKET_PROD 등)
2️⃣ 추후 작업할 내용
인프라 전환 완료 시 EC2 관련 배포 로직 제거 예정
3️⃣ 체크리스트
> chore: GitHub Actions develop 브랜치 S3 + CloudFront 배포 설정

- .github/workflows/deploy.yml
variable을 잘못 설정한 경우 재배포가 가능하도록 수동 프로덕션 배포를 활성화하고 deployment review를 설정합니다.
> ci: 수동 프로덕션 배포 활성화

- .github/workflows/deploy.yml
> chore: invalidation path 수정

- src/pages/qna-notice/page.tsx
> fix: 건의게시판 서브타이틀에 '해당 단위' 워딩 추가

- src/pages/main/containers/QnaSection.tsx
- resolved #595 
fix로 했어야 했낭
main에 머지 후 develop에 rebase하겠습니다.
> refactor: 메인페이지 '질의응답게시판' -> '건의게시판'으로 수정

- src/components/PostContent.tsx
- src/pages/human-rights/const.ts
- src/pages/human-rights/page.tsx
- src/pages/mypage/service-notice/component/ServiceNoticePostContent.tsx
- src/pages/mypage/service-notice/hooks/useSearchServiceNoticePosts.ts
- src/pages/mypage/service-notice/page.tsx
- src/pages/mypage/service-notice/schema.ts
- src/pages/qna-notice/const.ts
- src/pages/qna-notice/page.tsx
- src/pages/qna-notice/schema.ts
- resolved #587 
상세, 수정 페이지 공통 레이아웃 적용 후 마이페이지 내부에서 서비스 공지사항을 빼서 독립적인 페이지로 이동
> refactor: 목록 레이아웃 피드백 반영
