ssu-student-union/homepage-frontend

src/components/Board/BoardHead.tsx, src/components/Search/Search.tsx, src/components/ui/input.tsx, tailwind.config.js
- resolved #26 
1. 390px 이하 화면에서 Search 컴포넌트 변경 작업이 필요해 tailwind.config.js screens 객체 수정
2. 피그마 상의 검색창 반응형 구현을 위해 input 태그의 min-heigth 속성을 h-[46px] 으로 변경
3. BoardHead subtitle 속성은 단순  string이 아니라 ReactNode 로 수정
4. Search 컴포넌트 반응형 작업 수정
페이지 작업 하다보니 공통적으로 적용되어야 수정사항인거 같아 PR 올렸습니다. 수정 필요한 부분은 리뷰 남겨주세요!
=> fix: modified search boardhead components

src/template/BodyLayout.tsx, src/template/EditLayout.tsx, src/template/HeadLayout.tsx, src/types/layout/index.tsx
- resolved #43 
template 폴더 생성 후 게시판 페이지에 공통적으로 적용되는 레이아웃 템플릿 생성(게시글 상세 페이지 레이아웃 제외)
HeadLayout.tsx -> BoardHead 컴포넌트와 Search 컴포넌트 영역의 layout
BodyLayou.tsx -> 게시판 페이지의 메인 컨텐츠 영역과 pagination 컴포넌트, 글쓰기 버튼 영역의 layout
EditLayout.tsx -> 게시글 작성 페이지의 layout
`<EditLayout title="청원글 작성"> toast-ui 영역 </EditLayout>`
레이아웃 컴포넌트 사용 예제는 위와 같이 구현했습니다. 수정사항 있으시면 리뷰 달아주세용
=> feat: add layout template

src/components/Switch/index.tsx, src/pages/router.tsx
- resolved #49 
- `router.tsx`에서 대소문자가 잘못 입력되어있는 path 수정했습니다.
- `cn`을 적용해서 사용해서 사용처의 classname과 기존 classname이 머지될 수 있도록 하였습니다.
=> fix: switch classname 사용처에서 적용 안됨

src/components/FilterDropDown/FilterDropDown.tsx
- resolved #(52)
Components  - FilterDropDown 컴포넌트에 cn() 추가했습니다.
cn()을 적용해서 사용처의 classname과 기존 classname이 머지될 수 있도록 하였습니다.
=> fix: FilterDropDown에 cn() 추가

src/App.tsx, src/apis/getPetitionPostsTopLiked.ts, src/components/PostTextPetition/types/index.ts, src/hooks/useGetPetitionPostsTopLiked.ts, src/pages/main/containers/PetitionSection.tsx, src/types/getPetitionTopLiked.ts
-`getPetitionPostsTopLiked` 함수를 제작하였습니다.
- `useGetPetitionTopLiked` 함수를 제작하였습니다.
- ReactQuery default staleTime을 5분으로 설정하였습니다.
- `onGoingStatus` 타입을 string에서 서버에서 넘어올 수 있는 값들로만 한정지었습니다!
=> feat: 청원 인기 게시판 조회 api 호출 관련 함수

src/apis/client.ts, src/apis/kakaoLoginApi.ts, src/pages/kakao/containers/KakaoRedirect.tsx
- resolved #78 
카카오 로그인 로직 중 서버에서 받아온 토큰은 따로 accessToken key 로 로컬스토리지에 저장하도록 추가
axios 인터셉터 설정 및 토큰이 필요한 api 요청과 아닌 요청을 분리하기 위한 clientAuth 함수 새로 정의
토큰이 필요없는 api 요청 예시
`client.get('/api_endpoint');`
토큰이 필요한 api 요청 예시
`clientAuth({
method: 'get',
url: '/api_endpoint'
});`
=> feat: axios 인스턴스 객체 생성 및 카카오 로그인 로직 일부 수정

src/App.tsx, src/apis/client.ts, src/containers/common/Header/Header.tsx, src/pages/general/containers/GeneralRegisterSection.tsx, src/pages/kakao/containers/KakaoRedirect.tsx, src/pages/layout/headerLayout.tsx, src/pages/router.tsx
- resolved #261 
홈페이지 접근 시 
https://stu.ssu.ac.kr ->기존 페이지로 리다렉
https://stu.ssu.ac.kr/beta -> 아지위에서 작업한 신규 페이지로 리다렉
메인 페이지 라우팅 경로를 / -> /beta 로 변경
/ 경로로 라우팅 되던 로직들을 /beta로 리다이렉트 되도록 수정
=> hotfix: /beta 주소로 접근 가능하도록 허용

src/components/ui/button.tsx, src/pages/general/containers/GeneralRegisterSection.tsx
=> style: GeneralRegister input, button 길이 조절

src/components/ui/input.tsx, src/pages/general/containers/GeneralRegisterSection.tsx
=> style: GeneralRegister input, button padding, 상단 문구 크기 조절

package.json, src/hooks/useContentEditor.ts, src/pages/human-rights/edit/components/ContentEditor.tsx, src/pages/human-rights/edit/components/FileInput.tsx, src/pages/human-rights/edit/components/FileInputs.tsx, src/pages/human-rights/edit/components/FrontmatterEditor.tsx, src/pages/human-rights/edit/components/FrontmatterInput.tsx, src/pages/human-rights/edit/containers/ArticleFooter.tsx, src/pages/human-rights/edit/containers/ArticleHeader.tsx, src/pages/human-rights/edit/containers/Container.tsx, src/pages/human-rights/edit/form.ts, src/pages/human-rights/edit/page.tsx, src/pages/human-rights/schema.ts, src/pages/index.ts, src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx, src/pages/router.tsx, tsconfig.json, yarn.lock
- resolved #191 
- 신고자, 침해/피침해자 정보를 작성하기 위한 폼의 input인 `FrontmatterInput`을 작성했습니다.
- 기존 `Input`을 활용하려 했으나, 디자인이 인권신고게시판의 경우에만 달라 임의의 컴포넌트를 작성했습니다. 디자인 단계에서 수정이 필요해 보입니다.
- 신고자, 침해/피침해자 정보를 작성하기 위한 `key-value` 형식의 폼인 `FrontmatterEditor`를 작성했습니다.
- 기본적인 레이아웃 작업을 위한 `ArticleHeader`, `ArticleFooter`, `Container` 컴포넌트를 작성했습니다.
- 인권신고 열람 뷰 등에서 이미 일부를 사용하고 있으므로, epic branch로 병합한 후 컴포넌트 관계를 다시 설정할 예정입니다.
- 단일 파일 입력을 위한 `FileInput` 컴포넌트를 작성했습니다.
- `FileInput` 컴포넌트를 기반으로 다중 파일 입력이 가능한 `FileInputs`를 작성했습니다.
- `zod`와 `react-hook-form`을 결합하여 form 상태 관리 및 검증을 수행하는 `useHumanRightsForm()` 훅을 작성했습니다.
- 이 과정에서 zod Schema를 기반으로 `MockHumanRightsPostEditRequest` 타입을 작성했습니다.
- 타입 정의는 epic branch 병합 후 하나의 파일로 합칠 예정입니다.
- Editor의 이미지 처리 및 산출물을 담당하는 `useContentEditor(boardCode: string, ref: RefObject<Editor>)` 훅을 …
=> feat: 인권신고게시판 글 작성 뷰

package.json, src/pages/human-rights/edit/page.tsx, src/pages/human-rights/hooks/mutations/usePatchPost.ts
- related: #338
`usePatchPost`에 `id` 필드를 추가했습니다.
- yarn 버전을 `4.5.3`으로 업데이트했습니다.
=> fix(human-rights): `usePatchPost`에 `id` 추가

src/pages/human-rights/[id]/components/PostFooter.tsx, src/pages/human-rights/[id]/page.tsx, src/pages/human-rights/edit/components/FileInput.tsx
- `OFFICIAL` 타입의 댓글을 달았을 때 바로 업데이트 되지 않는 현상 수정
- `OFFICIAL` 타입의 댓글이 최신순으로 표시되지 않는 현상 수정
- `OFFICIAL` 타입의 댓글이 수정, 삭제 후 바로 반영되지 않는 현상 수정(* 삭제는 백엔드 버그로 반영 X)
=> fix(human-rights): `OFFICIAL` 타입의 댓글이 잘못 핸들링되는 문제

src/pages/human-rights/hooks/query/useGetUserInfo.ts, src/pages/human-rights/hooks/query/useSearchPosts.ts
`useSearchPosts`, `useGetUserInfo` 쿼리 키에 액세스 토큰을 추가하여 로그인/아웃 시에도 정상적으로 게시글 목록 및 사용자 정보가 표시되도록 하였습니다.
=> fix(human-rights): `useSearchPosts`, `useGetUserInfo` 쿼리 키에 액세스 토큰 추가

package.json, yarn.lock
현재 Vercel에서의 빌드는 강제로 `yarn@1.22.22`를 사용하고 있습니다. 최신 버전의 yarn berry와는 달리, yarn classic에서는 hoist 문제로 peerDependencies 중 하나가 다른 dependency의 peerDependency 보다 최신 버전일 경우, 구 버전의 peerDependency는 무시됩니다.
이로 인해 버전 호환성 문제가 발생할 수 있습니다.
최근 React 19 릴리즈로 인해 `@types/react-dom`에 정의된 `@types/react` peer dependency가 19 버전으로 업데이트 되었고(*`@types/react-dom`에는 `@types/react`의 버전 정의가 `*` 입니다), 따라서 `@types/react`의 버전이 19로 업데이트 되면서 `@types/react-slick`의 타입 정의와 충돌이 발생했습니다.
이 문제를 해결하기 위해 yarn classic의 resolutions 필드로 `react`와 `@types/react`의 버전을 18 버전으로 고정합니다.
최종적으로 문제를 해결하기 위해서는 `pnpm` 패키지 매니저로 마이그레이션을 고려하면 좋겠습니다.
=> fix(workspace): @types/react를 강제로 18 버전으로 사용하도록 변경

src/pages/audit/auditPatch/hook/useAuditPatch.ts, src/pages/lost-article/patch/hook/useLostPatch.ts, src/pages/partnership/partnershipPatch/hook/usePartnershipPatch.ts, src/pages/petition-notice/[id]/containers/PostPetitionDetailPostSection.tsx, src/pages/petition-notice/edit/containers/PetitionNoticeEditorSection.tsx, src/types/apis/get/index.tsx
- resolved #361
PostDetailResDto 타입 중 categoryName -> category 로 변경
PostPetitionDetailPostSection.tsx 타입 변경 적용
useAuditPatch.ts useLostPatch.ts usePartenership.ts 타입 변경 적용
=> fix: categoryName 필드 category 필드명으로 변경

src/components/BoardNew/edit/FileInput.tsx, src/hooks/new/mutations/useUploadFiles.ts, src/pages/data/queries.ts
- resolved #408 
파일 업로드 요청 시 자료집게시판의 경우 boardCode 값을 data로 설정해줬습니다.
자료집의 FileInput 스타일 변경
=> fix: 파일 업로드 요청 시 자료집게시판의 boardCode 값은 data로 설정

src/components/File/FileDownButton.tsx
- resolved #439 
결과물 이미지
```
**// fileUrl에서 확장자명을 추출한 후 대문자로 변경
const lastDotIndex = file.fileUrl.lastIndexOf('.');
const fileExtension = lastDotIndex !== -1 ? file.fileUrl.substring(lastDotIndex + 1) : '';**
return (
<a
className={cn(
buttonVariants(),
'h-[31px] w-[143px] rounded-[9px] bg-gray-200 text-[16px] font-medium text-gray-600',
'cursor-pointer overflow-hidden text-ellipsis whitespace-nowrap px-2 hover:text-white',
className
)}
title={file.fileType}
href={file.fileUrl}
download={file.fileName}
>
**{`${file.fileType} ${fileExtension.toUpperCase()}`}**
</a>
);
```
확장자명 앞에만 .이 있는 게 아니라서 마지막 .을 기준으로 문자열 끝까지를 확장자명으로 추출했습니다.
디자인에는 확장자명을 대문자로 표현해서 toUpperCase()로 대문자화 했습니다.
더 좋은 방법 있으면 말씀해주세요 💀
=> feat: fileUrl에서 확장자명 추출 후 fileType 뒤에 삽입 #439

src/containers/common/Header/Header.tsx
- resolved #479 
Header가 소개페이지 Navigator 컴포넌트 밑으로 가는 현상 때문에 z-index 값 조정했습니다
=> hotfix: navigator 컴포넌트와 header 컴포넌트 z-index 조정

src/pages/qna-notice/[id]/page.tsx, src/pages/qna-notice/[id]/types.ts, src/pages/qna-notice/edit/page.tsx, src/pages/qna-notice/page.tsx
- resolved #448
- 질의응답게시판 페이지
- 로그인 하지 않은 경우 글쓰기 버튼 표시
- 비로그인 사용자가 글쓰기 버튼 클릭 시 로그인 페이지로 이동
- 로그인 사용자가 글쓰기 버튼 클릭 시 질의응답 게시글 작성 페이지로 이동
- 질의응답게시판 작성 페이지
- 질문 대상 선택 및 세부 대상 선택 select 모바일 화면에서 스타일 깨지는 문제 수정
- 질의응답게시판 상세 페이지
- 자치기구 게시글 작성 및 수정 시 이용하는 queryClient 로직 상세 게시글 데이터에 대한 쿼리키에 누락된 boardCode 추가
백엔드 작업이 완료됐다고 전달 받았으나 아직 적용이 안된 상태
-> 오피셜 댓글에 대한 isDelete 속성 추가 후 로컬에서 테스트 완료
---------
- resolved #(issue_num)
=> fix: 질의응답게시판 QA 적용 (#482)

src/pages/main/page.tsx, src/pages/mypage/service-notice/component/ServiceNoticeTab.tsx, src/pages/qna-notice/[id]/page.tsx, src/pages/router.tsx
- resolved #486 
- **Header에 애니메이션을 적용하면서 생성했던 더미 Header로 인해 발생한 문제였기에 이전 코드로 변경하여 오류 수정**
- src/pages/router.tsx => MainPage에 대한 Route 태그를 Layout에 대한 Route 태그 내부로 이동
- src/pages/main/page.tsx => 더미 Header와 Footer 제거
- **긴급공지가 Navigation의 드롭다운을 가리는 문제 해결**
- src/pages/mypage/service-notice/component/ServiceNoticeTap.tsx 긴급 공지에 대한 z-index 값을 변경하여 Navigation의 드롭다운을 가리지 않도록 수정
- **렌더링 시마다 댓글 데이터를 리페칭하지 않아 권한 업데이트가 안되어 댓글 작성창이 안뜨는 문제 해결**
- src/pages/qna-notice/[id]/page.tsx => 렌더링 시마다 댓글 데이터 리페칭
```ts
const {
data: comments,
isLoading: isCommentsLoading,
isError: isCommentsError,
error: commentsError,
} = useGetComments<QnaComment>({ postId, type: '최신순', queryOptions: { refetchOnMount: 'always', staleTime: 0 } });
```
=> hotfix : 총학과 중운위 댓글 작성 불가 문제, 스크린 넓이 1440px부터 로그인 로그아웃 제대로 반영 안되는 문제

src/pages/qna-notice/page.tsx
- resolved #492 
질의응답게시판 글쓰기 버튼 클릭시
시범운영 기간이 종료되었습니다. 곧 오픈 예정이니 다음에 이용해주세요
문구가 표시된 alert 창이 뜨도록 수정했습니다.
```ts
function navigateToWrite() {
alert('시범운영 기간이 종료되었습니다. 곧 오픈 예정이니 다음에 이용해주세요');
// if (isLogin) {
//   navigate('/qna/edit');
// } else {
//   navigate('/register');
// }
}
```
=> chore: 질의응답게시판 글쓰기 버튼 클릭시 시범운영 alert창 띄우기

src/pages/main/containers/FloatingButtons.tsx, src/pages/main/page.tsx
- resolved #527 
1. Counsel이라는 뜻이 적절하지않은 거 같아서, FloatingButtons라고 바꾸었습니다.
2. FloatingButtons의 z-index를 ServiceNoticeTab의 아래로 변경했습니다.
=> fix: 플로팅섹션 조금 아래로 #527

src/pages/layout/registerLayout.tsx, src/pages/register/step/scouncil/page.tsx
- resolved #532 
Passu에서 넘어올 때 자치기구 로그인 성공 시 passu로 리다이렉트하는 부분을 각주 처리하였는데 이 부분 필요하여서 다시 추가해놓았습니다.
추가로 #526 로그인 성공 시 토큰 저장 로직 추가 pr이 누락되어서 그 부분도 추가하였습니다.
=> fix: passu 리다이렉트 자치기구 로그인 기능 추가

src/pages/mypage/service-notice/component/ServiceNoticeTab.tsx
- resolved #534 
서비스공지사항 탭 헤더와 벌어지는 이슈 수정했습니다.
=> refactor: ServiceNoticeTab Header와 벌어짐 해결

src/containers/common/Header/Header.tsx, src/containers/common/Header/component/HeaderSheet.tsx, src/containers/common/Header/const/pathData.tsx
- resolved #545 
이전 홈페이지 호스팅 중단에 따라 Header 레이아웃에서 '이전 홈페이지'를 삭제하고 관련 코드들을 정리했습니다.
=> chore: Header 이전 홈페이지 제거

src/pages/notice/edit/component/ImageDropzone.tsx, src/pages/notice/edit/container/noticeEditImageSection.tsx
- resolved #566
10MB 넘는 이미지 첨부 시 이렇게 에러 문구 뜨게 했습니다. 사라지는 조건이 애매해 3초 후 없어지게 했습니다.
=> feat: 공지사항 이미지 업로드 시 고용량 제한 문구 추가

package.json, src/pages/main/containers/NoticeSection.tsx, src/pages/notice/edit/component/ImageDropzone.tsx, src/pages/notice/edit/container/noticeEditImageSection.tsx, src/pages/notice/edit/container/noticeEditSubmitButton.tsx, src/pages/notice/state.ts, yarn.lock
- resolved #568
공지사항 게시판 이미지 input에 적용해줬습니다. 
이미지 압축 함수입니다. 1MB 이하로 압축하고, 최대 너비 또는 높이를 1080px로 설정합니다. 형식은 WebP로 변환합니다.
```
const compressImages = async (files: File[]) => {
setCompressing(true);
setCompressError(false);
const compressedFiles: File[] = [];
for (const file of files) {
try {
const compressedBlob = await imageCompression(file, {
maxSizeMB: 1,
maxWidthOrHeight: 1080,
useWebWorker: true,
fileType: 'image/webp',
});
const baseName = file.name.replace(/\.[^/.]+$/, '');
const webpName = `${baseName}.webp`;
const finalFile = new File([compressedBlob], webpName, {
type: compressedBlob.type || file.type,
lastModified: Date.now(),
});
compressedFiles.push(finalFile);
} catch (_error) {
setCompressError(true);
}
}
setCompressing(false);
return compressedFiles;
};
```
압축 상태는 state.ts의 …
=> feat: 이미지 파일에 Browser-image-compression 적용
